### ISSUE TITLE
python manage.py makemigrations && python manage.py migrate

### ISSUE THREAD

**Issue by 51ISI** [charlesxs/cmdb#2]
[root@localhost cmdb]# python manage.py makemigrations && python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/cmdb/cmdb/models.py", line 7
SyntaxError: Non-ASCII character '\xe6' in file /opt/cmdb/cmdb/models.py on line 7, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by charlesxs** [comment]
是否是python 3.4 以上的版本

**Comment by 51ISI** [comment]
已经解决。  python 版本问题
________________________________
发件人: Charles <notifications@github.com>
发送时间: 2018年12月3日 11:34
收件人: charlesxs/cmdb
抄送: OwenTest; Author
主题: Re: [charlesxs/cmdb] python manage.py makemigrations && python manage.py migrate (#2)


是否是python 3.4 以上的版本

―

**Comment by 51ISI** [comment]
后续还维护么  增加么？哈哈~
________________________________
发件人: Charles <notifications@github.com>
发送时间: 2018年12月4日 14:19
收件人: charlesxs/cmdb
抄送: OwenTest; Author
主题: Re: [charlesxs/cmdb] python manage.py makemigrations && python manage.py migrate (#2)


Closed #2<https://github.com/charlesxs/cmdb/issues/2>.

―
